project:
  type: website
  resources: static

website:
  title: "Ken Arnold @ Calvin University"
  navbar:
    right:
      - pubs.qmd
      - text: CV
        href: static/kcarnold_cv.pdf
      - icon: github
        href: https://github.com/kcarnold
      - icon: twitter
        href: https://twitter.com/kcarnold
format:
  html:
    theme: cosmo
    css: styles.css



