project:
  type: website

website:
  title: "Ken Arnold @ Calvin University"
  navbar:
    right:
      - publications.qmd
      - about.qmd
      - icon: github
        href: https://github.com/kcarnold
      - icon: twitter
        href: https://twitter.com/kcarnold
format:
  html:
    theme: cosmo
    css: styles.css



