project:
  type: "website"
  output-dir: _site
  resources: 
    - CNAME
    - static/*
website:
  title: "Ken Arnold (Calvin U)"
  site-url: "https://kenarnold.org/"
  navbar:
    right:
      - posts.qmd
      - pubs.qmd
      - ideas.qmd
      - text: CV
        href: static/kcarnold_cv.pdf
      - icon: github
        href: https://github.com/kcarnold
      - icon: twitter
        href: https://twitter.com/kcarnold
  page-navigation: true
  google-analytics: "G-6SPV9Y5XFG"
  reader-mode: true
format:
  html:
    theme: cosmo
    css: styles.css



