---
title: "Projects"
---

## AI for Writers

We develop tools to help writers serve their readers better without putting words in their mouths.

Publications:

- [Supporting Revision with AI-Generated Views](/pubs/haigen24/index.qmd) (HAI-GEN workshop at IUI 2024)
- [Generative Models can Help Writers without Writing for Them](/pubs/iui21-help-writers/index.qmd) (HAI-GEN workshop at IUI 2021)
- [Cognitive Engagement with AI Writing Suggestions](/pubs/cognitive-engagement/index.qmd) (internal poster fair 2024)
- [Interacting with Conditional Distributions to Enact Desired Edits](/pubs/enact-edits/index.qmd) (in preparation, *demo available*)

Also, students are currently working on deploying the Textfocals sidebar (described in the publications above) as part of a broader study; let me know if you're interested in participating.

## Predictive Text

We study how predictive text shapes what people write and develop interfaces that help people use it differently.

Publications:

- [Predictive Text Encourages Predictable Writing](/pubs/predictable/index.qmd) (IUI 2020)
- [Sentiment Bias in Predictive Text Recommendations Results in Biased Writing](/pubs/sentiment-bias/index.qmd) (GI 2018)
- [On Suggesting Phrases vs. Predicting Words for Mobile Text Composition](/pubs/phrase-suggestion/index.qmd) (UIST 2016)


See the [Writing Prototypes](https://huggingface.co/spaces/kcarnold/writing-prototypes) space for one demo that re-imagines the chatbot interface as a predictive text interface.

## Educational Technology

- [Moodle-Palette](https://github.com/kcarnold/Moodle-Palette) is a keyboard-based interface for Moodle. It also serves as a playground for various ways of incorporating privacy-sensitive AI into instructors' workflows for content creation and feedback.
- [zylabs-libs](https://github.com/kcarnold/zylabs-libs) is a collection of Python shim code to help instructors develop ZyLabs questions that give students better feedback.
- [Calgen](https://github.com/kcarnold/calgen): a tool for helping instructors (and eventually students) import their course schedules into their calendars.

## Other Projects

- [X32 channel-mover script](https://github.com/kcarnold/channel-mover): a Streamlit app for moving channels around on a Behringer X32 soundboard.
- [Nanomixer](https://github.com/nanomixer/nanomixer): A digital audio mixer, with ADAT I/O and processing on FPGA and web-based control

::: {.content-hidden}
•	Medical data science: If medical records could capture the treatment decision-making process (instead of just the decisions made), we could develop causal estimators to disambiguate whether outcomes were because of or in spite of the treatment decisions. These estimators could be used in two kinds of applications: rare conditions where data is sparse, and identifying potential disparate effects of standard-of-care practices where, despite an average-positive treatment effect, effects on a minority group might be negative.
•	Tooling for data science. Computational notebooks are ubiquitous in data science practice, but the notebook interaction paradigm is limited in its support for iteratively constructing abstractions, code testing, non-linear workflows, curation of process artifacts, computationally intensive operations, visualizations of intermediate steps, and correct statistical analyses. I have various ideas for improvements to notebooks that I would like to explore with interested collaborators. Although I had most of these ideas before the advent of LLMs, those tools offer additional potential (e.g., helping to write tests and offer feedback on code, generating and refining plots of intermediate data, generating sample data, reminding analysists about assumptions of statistical tests, etc.)
:::
