---
title: "Why Calvin?"
date: "2023-02-14"
draft: true
---

God has his people everywhere; as the Belgic Confession reminds us, God preserved 7000 who had not bowed the knee to Baal in the time of Elijah. So why a Christian school? And why Calvin in particular?

I have 3 reasons for asking this question:

1. Should I stay here?
2. Why should students come here, especially for our online graduate programs (I'm involved in the Masters in Data Science and the MBA), and other programs and events that Calvin organizes?
3. Should we send our kids to Christian schools?

## Asking questions

What are we forming in ourselves and our communities through our choices and visions about technology? How does that compare with what is *good* to pursue in these areas? How then should we individually and collectively choose to use and develop technology?

I've studied at three secular universities (Cornell, MIT, and Harvard), and I can say honestly that questions like these would not be foreign at those places. In fact I've learned a lot (and could learn a lot more) from how my research group at Harvard started addressing some of these questions more directly after I graduated. But you can succeed as a student and scholar in those places without asking these questions. You can't avoid these questions at Calvin.

## Grounded but Diverse

Ironically the common grounding in the Reformed Christian tradition actually welcomes a wide range of viewpoints. In fact I see Christianity as welcoming, even perhaps *commanding*, a diversity of particular interpretations and emphases.

It is not popularly accepted in secular circles to talk about any sort of universal standard of a good life. But the Reformed Christian tradition that Calvin embraces has many well-developed concepts in this area: *shalom*. *justice*. Humanity in the *image of God*. These concepts are grounded in ancient texts that are still somehow alive today. They are both individual and communal. They imply both rights and responsibilities. There are a wide range of specific ways that these concepts work out, but the Bible gives some specific examples of how it has worked in historical situations that we can learn a lot from despite our huge cultural distance. These things are "[only the grammar of virtue](https://www.goodreads.com/quotes/10402797-of-course-there-are-universal-rules-to-which-all-goodness)" with diverse ways that this actually works out.

Secular considerations of tech justice are asking some very good questions and providing some insightful and important critiques of what's going on in technology. I think Christian scholars can learn a lot from these. But these discussions remain somewhat narrow and risk becoming cliche. I mean no insult by this, but when I attempted to use GPT-3 to help write my own bio, it suggested plausible "tech for good" language, suggesting that the outward appearance of working for some sort of good is now part of an identity marker that any tech researcher must check off.

Justice has an aspect of what we *owe* to each other, not just who is in power, whose voices are foregrounded or backgrounded (although these are important questions). Identity has an aspect of how our decisions form and reflect our own character and how these decisions affect others, not just demographic checkboxes. etc.

## Curiosity and Beauty

(MIT students have a culture of valuing knowledge about the world just because it's cool, not always linked to what we can do with it. The "hack" culture reflects something of this; they do things just because it can be done. There's also lots of detailed visions of how technology can help make a better world.)

## Formation

- Character, Virtue
- Habits of thoughtful questioning, neither full embrace nor bare-knuckled criticism

## Relational

I still struggle to learn my students' names and stories. (Ironically this is actually easier online, since every interaction has the student's name attached.)
