---
title: "Typical Assumptions of ML-Based AI"
draft: true
---

## Experience: IID

The world can be expressed as a large number of mostly indepdentent experiences. They are, at best, loosely ordered. We generally get as many attempts at a problem as we need. Mistakes are never fatal; just respawn and try again.

Otherwise stated:

- People are basically interchangeable with each other and with machines
- Data are independent and identically distributed.

In contrast:

  - life is continuous and diverse; "his mercies are new every morning"
  - Intelligence seems to *require* engagement with the world. You can't sit on the couch and become intelligent
    - Even the mimicry systems that pretrain on watching / reading make a very challenging exercise out of sitting on the couch: trying to guess the next word

## Objective: Loss

- It’s meaningful to define a single number called loss.

Reductionism:

- We can reduce intelligence to input-output behavior
- We can quantify intelligence with a few benchmark numbers
- In general looking at average case behavior is good (as opposed to resilience or reliability)


## Scale: required

- Models must be big.
- Bigger is better.

## Framing: Packaged

Assumption: the world comes packaged into problems with clear input, output, and objectives. Often the actions to be taken are choices among discrete options (e.g., which controller button to press in a video game, which category to label an image, what word to choose next).

- Image classification: we're given images that somebody cares about, each image has meaningful things in it, we know what the options are for those things, there's a right answer that we're aiming for.
- LLMs: the person has a specific question/request/desire that the LLM is supposed to fulfill; it can be fulfilled in a short interaction with a chat window on a screen (or short voice conversation)

Complexity: generating sequences can provide some open-endedness to the outputs.

In contrast:

- Adam named the animals ([Genesis 2:20](https://www.biblegateway.com/passage/?search=gen%202%3A20&version=NIV&interface=print)).
- God's command to living things, especially to humans, was to "be fruitful", "subdue", and "rule over" ([Genesis 1:28](https://www.biblegateway.com/passage/?search=Genesis%201%3A28&version=NIV&interface=print))
- We make new potential.

## Other


- Input an output behavior is all that matters, we don’t care about internal logic, internal thinking, or having an accurate model of the world that’s faithful to how things actually work
- The world is basically predictable (and everything that isn't we can just call noise and ignore)


