---
title: "Honor and GenAI"
description: "Technology can be re-formed into a tool for honoring others."
date: 2024-05-22
draft: 1
---

> Let love be genuine. Abhor what is evil; hold fast to what is good. Love one another with brotherly affection. Outdo one another in showing honor. (**Romans 12:9-10 ESV**)

> Lord’s Day 40, Q & A 105
> 
> Q. What is God’s will for you
> in the sixth commandment?
>
> A. I am not to belittle, hate, insult, or kill my neighbor—
>  not by my thoughts, my words, my look or gesture,
> and certainly not by actual deeds—
> and I am not to be party to this in others
>
> [Heidelberg Catechism](https://www.crcna.org/welcome/beliefs/confessions/heidelberg-catechism#toc-the-ten-commandments)

The contrast of honor and shame is prevalent in the Biblical story. People are encouraged to honor God, but also to honor each other. And those who hope in Jesus will not be put to shame, but will receive honor along with him when our hope is ultimately vindicated.

## AI tech can be a a tool to dishonor:

I can dishonor you by **perceiving** you only through the "coded gaze" of an ML model. This can lead me to make false, or at least oversimplified (reductionist), assumptions about you. Examples: screening resumes, judging students' work, ...

I can dishonor you by spitting generated text in your face.
James advises us to be "quick to listen, slow to speak" (James 1:19). But generating from LLMs encourages us to speak lots quickly; it’s "productive".
When I pass off generated words to you:

- I’m dishonestly implying these are "my" words.
- I’m not thinking about whether they’re ultimately true.
- I’m assuming that a machine knows more than you.
- I’m making you read something that’s full of assumptions

Knowing that some words are AI generated makes people more skeptical of even real words.
(Liar’s Dividend)

Finally, I can dishonor you by doing things that affect you without thinking about you.
TODO write more here


## How could communication tools help us honor each other?

Most simply, AI tools could help us check ourselves against the obvious forms of some of the evils of the tongue, like slander. “From the same mouth come blessing and cursing; my brothers and sisters, this ought not to be so” (James 3:10).; “do not speak evil against one another” (James 4:11). An AI editor could check if what we’re saying could be interpreted as cursing or slandering anyone, or identify places where our writing is boastful or not gentle. The system would be necessarily error-prone: it could not detect the hypocrisy of gentle words but a deceptive heart (Proverbs), and it might flag constructive criticism as evil speech. But taking a moment to check our speech against a few known fruits of the fire of Gehenna (James 3:6) could give faithful writers an opportunity to “examine their work”. Some email add-ins already let us evaluate the "tone" of our messages; a slander-checker could fit right in, but it might require more detailed explanation of how our writing might be (mis)-construed, in order to catch the problem.

Things we write may not be intentionally evil, but may still not honor the time or thinking of our readers if they are not clear. Writing tools can help us honor our readers’ attention and thought by helping to remove quirks of text that distract, or clarify language that takes extra effort to understand. Tools like Grammarly or Microsoft Editor do this reasonably well at the scale of phrases or sentences; other tools could help writers identify larger-scale issues like inconsistencies, ambiguous interpretations, using terms without definition, etc.

Things we write might also simply be wrong or incomplete. Writing tools could help us honor our readers by helping us notice unsubstantiated statements, overconfidence, assumptions that are made, etc. Current writing tools don’t help us identify these things at all; in fact they tend to [encourage us to be overly confident](https://christianscholars.com/grammarly-ai-editors-chatgpt-and-the-pedagogical-perils-of-writing-with-confidence/).

Writing as a technology puts the people who will receive it at a distance. This is useful for us for various reasons (we can edit, refine our thoughts; readers can skim or re-read as desired, etc.), but it does allow us to avoid thinking about our “audience”. But what writing does in someone else’s head is ultimately the point of the exercise of writing. 

TODO write more here