---
title: "AI and Writing: Do we speak the words of stochastic parrots?"

authors:
- Kenneth C. Arnold

date: "2022"

# Publication name and optional abbreviated publication name.
publication: ACMS 2022
publication_short: ACMS 2022

abstract: "Mimicry pervades the design and implementation of generative AI systems. I reflect on this observation from a Christian perspective and outline various approaches to 'redeem' how we use the artificial parrots in writing."

categories: ["HCI", "NLP"]
---

[PDF](arnold2022mimicry.pdf) {{< meta publication_short >}}

## Abstract

Generative Artificial Intelligence systems have recently and publicly become increasingly comparable
to the capabilities of many humans in some domains, such as text and image generation.  These systems are
rapidly being incorporated into human contexts, for example as phone keyboards and email apps offer us
AI-generated suggestions of words and even complete phrases to enter with a single tap or swipe.  But
these suggestions don't just reduce physical effort; they reduce cognitive effort: we can accept a
suggested phrase before even thinking about what to say.  In this article, I first describe how mimicry
pervades the design and implementation of generative AI systems and expound on some of the implications thereof.
I then critique how these systems are designed and implemented in light of our God-given identity, a
biblical perspective on mimicry, and a reflection on virtue.  I finally outline several
``swords-to-plowshares'' approaches that re-form generative AI technologies to support human thinking in
writing tasks: *structural editing tools*, *writer-directed questions* to support writers
without speaking for them, and *visualizations* to enable writers to reflect on their work.