---
title: "Reflective Communication"
date: 2025-01-14
categories: ["llm", "interaction", "reflection"]
description: "GenAI can help you reflect on how your communication serves others."
featured: 0
---

This post is part of a [series of GenAI in Reflective Mode](/posts/reflective-ai/).

> Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves, not looking to your own interests but each of you to the interests of the others. In your relationships with one another, have the same mindset as Christ Jesus: Who, being in very nature God, did not consider equality with God something to be used to his own advantage; rather, he made himself nothing by taking the very nature of a servant... ([Philippians 2:3-7 NIV](https://www.biblegateway.com/passage/?search=Philippians+2%3A3-7&version=NIV))

Suppose you're writing an email communicating a decision you've made to a group of people. Generative mode says: AI can help you write that email more quickly (just say what you want to communicate and it'll write it out in nice language), fix up your grammar and tone to make it sound kind and empathetic, and let you get on with your day. But reflective mode says: let's think through how people are going to react to this. How will it make them feel? What's unclear or ambiguous? What's missing? Will this decision affect them in ways that I didn't think about? Were there some perspectives that weren't heard while we were making this decision?

Fundamentally, reflective-mode AI is about *humility*. When we recognize that human cognition isn't just *inefficient* but *flawed*, we can take steps to address those flaws. Reflective-mode AI can address cognitive flaws in various ways:

- Helping us recognize *when to slow down* because our actions affect others.
- Prompting us to reflect on our actions in ways that we ourselves, our teammates, or others have identified as healthy practices.
- Providing concrete examples of these reflections, based on the accumulated wisdom of human authors around the world, over time.
- Helping us think through things from different perspectives, either perspectives of particular people or "thinking hats".

Here's a quick and dirty Streamlit prototype of the idea (made with help from Claude, and using the Claude API). [source code](https://github.com/kcarnold/reflective-communication)

::: {.column-screen-right}

<iframe
    width="100%"
    height="700"
    src="https://reflective-communication-4c5irjgahhmnyxbqqyhmxb.streamlit.app/?embed=true"
    frameborder="0"
    allowfullscreen></iframe>

:::

The prototype doesn't fully capture all of the ideas, but is a place to start. In particular, one important thing missing is how **teams can curate reflective practices**, so that the practice is meaningful, contextually appropriate, and aligns with the team's values and processes.
