---
title: "GenAI in Reflective Mode"
date: 2025-01-14
categories: ["llm", "interaction", "reflection"]
description: "GenAI can help you reflect on your work, not just get it done faster."
featured: 0
---

When you hear "generative AI", you probably think about getting things done for you. And generally that's what we use computers for: getting things done faster or more accurately. But I argue there's another valuable use of computing that you should consider: reflecting on your own work.

Let's be concrete. Suppose you're writing an email communicating a decision you've made to a group of people. Generative mode says: AI can help you write that email more quickly (just say what you want to communicate and it'll write it out in nice language), fix up your grammar and tone to make it sound kind and empathetic, and let you get on with your day. But reflective mode says: let's think through how people are going to react to this. How will it make them feel? What's unclear or ambiguous? What's missing? Will this decision affect them in ways that I didn't think about? Were there some perspectives that weren't heard while we were making this decision?

Fundamentally, reflective-mode AI is about *humility*. When we recognize that human cognition isn't just *inefficient* but *flawed*, we can take steps to address those flaws. Reflective-mode AI can address cognitive flaws in various ways:

- Helping us recognize *when to slow down* because our actions affect others.
- Prompting us to reflect on our actions in ways that we ourselves, our teammates, or others have identified as healthy practices.
- Providing concrete examples of these reflections, based on the accumulated wisdom of human authors around the world, over time.
- Helping us think through things from different perspectives, either perspectives of particular people or "thinking hats".

Here's a quick and dirty Streamlit prototype of the idea (made with help from Claude, and using the Claude API). [source code](https://github.com/kcarnold/reflective-communication)

::: {.column-screen-right}

<iframe
    width="100%"
    height="700"
    src="https://reflective-communication-4c5irjgahhmnyxbqqyhmxb.streamlit.app/?embed=true"
    frameborder="0"
    allowfullscreen></iframe>

:::

The prototype doesn't fully capture all of the ideas, but is a place to start. In particular, one important thing missing is how **teams can curate reflective practices**, so that the practice is meaningful, contextually appropriate, and aligns with the team's values and processes.

Other things we could be reflecting on:

- in **teaching**:
    - for a specific assignment: what will likely confuse students? what clarifying questions will they have? where might they get stuck?
    - for a unit: how do my materials line up with the learning objectives? what learning objectives will students connect with most or least?
- in **research**:
  - what about this paper will confuse reviewers?
  - what part of my experiment design makes least sense? is most likely to fail?
  - what assumptions am I making that I haven't written down?
- in **presentations**
  - what will the audience be most interested in? what will they be most confused by?
  - is anything I'm saying likely to be misinterpreted or to offend someone?

(many more are possible; just ask an AI to continue this list!)

We were made to be makers--not just of things or text, but of ideas, questions, hypotheses, observations.

Ultimately, it's not about getting the right answers faster. It's about asking better questions, the sort of questions that will help us act virtuously.

Let's use computing power to help us think *better*.

Related: [AI Should Challenge, Not Obey](https://dl.acm.org/doi/10.1145/3649404)
